### ISSUE TITLE
querying the bot with "!lineart" does not work

### ISSUE THREAD

**Issue by jkowalleck** [k4cg/Rezeptionistin#18]

**Comment by gammenion** [comment]
This is working as in latest pull #22

**Comment by mojoaxel** [comment]
Hell! No! Sis is de moust imbordend fihtscher, überhaubt! Blease maik it ran agein!

**Comment by noqqe** [comment]
@gammenion @mojoaxel. You are both wrong :P 

It works. But only in a channel message. Not by querying the user Rezeptionistin directly.

**Comment by gammenion** [comment]
@noqqe ok! I added it to this pull request.

**Comment by noqqe** [comment]
works since f5e4b301aecaf4f6f375eb1918789fd0d458601e
