### ISSUE TITLE
Openstatus plugin does not work

### ISSUE THREAD

**Issue by noqqe** [k4cg/Rezeptionistin#26]
What i think is that somehow the plugin does not get loaded at all. even if i put print statements in the **init**.py, nothing is shown in the log.

**Comment by gammenion** [comment]
I found a mistake in the on_privmsg method where a parameter "channel" was added, as well as calling the send_message with parameter "channel" instead of "user_nick". I will make a new pull request with the fix. But maybe this is being refactored already.

**Comment by noqqe** [comment]
also fixed.
